--
-- Proculas: DeathKnight Procs
-- Created by Clorell of Hellscream [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

if select(2, UnitClass("player")) ~= "DEATHKNIGHT" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasDeathKnight = Proculas:NewModule("DeathKnightProcs")

if not Proculas.enabled then
	return nil
end

local PROCS = {
	[50466] = {
		name = "Death Trance!",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 1 
		-- name: Death Trance! 
		-- type: DEATHKNIGHT 
	},
	[50447] = {
		name = "Bloody Vengeance",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 2 
		-- name: Bloody Vengeance 
		-- type: DEATHKNIGHT 
	},
	[50448] = {
		name = "Bloody Vengeance",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 3 
		-- name: Bloody Vengeance 
		-- type: DEATHKNIGHT 
	},
	[50449] = {
		name = "Bloody Vengeance",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 4 
		-- name: Bloody Vengeance 
		-- type: DEATHKNIGHT 
	},
	[52424] = {
		name = "Retaliation",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 5 
		-- name: Retaliation 
		-- type: DEATHKNIGHT 
	},
	[50421] = {
		name = "Scent of Blood",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 6 
		-- name: Scent of Blood 
		-- type: DEATHKNIGHT 
	},
	[51789] = {
		name = "Blade Barrier",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 7 
		-- name: Blade Barrier 
		-- type: DEATHKNIGHT 
	},
	[55744] = {
		name = "The Dead Walk",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 8 
		-- name: The Dead Walk 
		-- type: DEATHKNIGHT 
	},
	[53136] = {
		name = "Abominable Might",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 1,
		-- Proc Info
		-- ID: 86 
		-- name: Abominable Might 
		-- type: DEATHKNIGHT 
	},
	[53386] = {
		name = "Cinderglacier",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 217 
		-- name: Cinderglacier 
		-- type: DEATHKNIGHT 
	},
	[55789] = {
		name = "Improved Icy Talons",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 1,
		-- Proc Info
		-- ID: 218 
		-- name: Improved Icy Talons 
		-- type: DEATHKNIGHT 
	},
	[51124] = {
		name = "Killing Machine",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 219 
		-- name: Killing Machine 
		-- type: DEATHKNIGHT 
	},
	[59052] = {
		name = "Freezing Fog",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 220 
		-- name: Freezing Fog 
		-- type: DEATHKNIGHT 
	},
	[53365] = {
		name = "Rune of the Fallen Crusader",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 256 
		-- name: Rune of the Fallen Crusader 
		-- type: DEATHKNIGHT 
	},
	[67117] = {
		name = "Unholy Might",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 321 
		-- name: Unholy Might 
		-- type: DEATHKNIGHT 
	},
	[63583] = {
		name = "Desolation",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 354 
		-- name: Desolation 
		-- type: DEATHKNIGHT 
	},
	[66800] = {
		name = "Desolation",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 354 
		-- name: Desolation 
		-- type: DEATHKNIGHT 
	},
	[66801] = {
		name = "Desolation",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 354 
		-- name: Desolation 
		-- type: DEATHKNIGHT 
	},
	[66802] = {
		name = "Desolation",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 354 
		-- name: Desolation 
		-- type: DEATHKNIGHT 
	},
	[66803] = {
		name = "Desolation",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 354 
		-- name: Desolation 
		-- type: DEATHKNIGHT 
	},
}

function ProculasDeathKnight:OnInitialize()
	Proculas:addProcList('DEATHKNIGHT',PROCS)
end
