--
-- Proculas: DeathKnight Procs
-- Created by Mcstabin of Hellscream [US]
--
-- Generated by Proc DB 3.0
--

if select(2, UnitClass("player")) ~= "DEATHKNIGHT" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local DeathKnightProcs = Proculas:NewModule("DeathKnightProcs")
if not Proculas.enabled then
	return nil
end

local PROCS = {
	[50421] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESHED"},onSelfOnly=0,procId="41"}, -- Proc #41: Scent of Blood
	[50463] = {types={"SPELL_DAMAGE"},onSelfOnly=0,procId="42"}, -- Proc #42: Blood-Caked Blade
	[50452] = {types={"SPELL_SUMMON"},onSelfOnly=0,procId="43"}, -- Proc #43: Blood Parasite
	[51124] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESHED"},onSelfOnly=0,procId="44"}, -- Proc #44: Killing Machine
	[59052] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESHED"},onSelfOnly=0,procId="45"}, -- Proc #45: Rime
	[81340] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESHED"},onSelfOnly=0,procId="46"}, -- Proc #46: Sudden Doom
	[81141] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESHED"},onSelfOnly=0,procId="47"}, -- Proc #47: Crimson Scourge
}

function DeathKnightProcs:OnInitialize()
	Proculas:addProcList('DEATHKNIGHT',PROCS)
end