--
-- Proculas: Druid Procs
-- Created by Idunno of US Nagrand
--
-- Generated by Proc DB 3.0
--

if select(2, UnitClass("player")) ~= "DRUID" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local DruidProcs = Proculas:NewModule("DruidProcs")
if not Proculas.enabled then
	return nil
end

local PROCS = {

}

function DruidProcs:OnInitialize()
	Proculas:addProcList('DRUID',PROCS)
end
