--
-- Proculas: Enchant Procs
-- Created by Clorell of US Hellscream
--
-- Generated by ProcDB 2.0
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local EnchantProcs = Proculas:NewModule("EnchantProcs")

if not Proculas.enabled then
	return nil
end

local PROCS = {
	[4083] = {spellIds={"74221"},types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=0,procId="10"}, -- Proc #10: Hurricane
}

function EnchantProcs:OnInitialize()
	Proculas:addProcList('ENCHANTS',PROCS)
end