--
-- Proculas: Gem Procs
-- Created by Clorell/Keruni of Argent Dawn [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasGem = Proculas:NewModule("GemProcs")

local PROCS = {
	[55382] = {
		itemID = 41401,
		types = {"SPELL_ENERGIZE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 42 
		-- name: Insightful Earthsiege Diamond 
		-- type: gem 
	},
}

function ProculasGem:OnInitialize()
	Proculas:addProcList('Gems',PROCS)
end
