--
-- Proculas: Gem Procs
-- Created by Clorell of Hellscream [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasGem = Proculas:NewModule("GemProcs")

if not Proculas.enabled then
	return nil
end

local PROCS = {
	[55382] = {
		itemID = 41401,
		types = {"SPELL_ENERGIZE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 42 
		-- name: Insightful Earthsiege Diamond 
		-- type: gem 
	},
	[55341] = {
		itemID = 41385,
		types = {"SPELL_HEAL"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 322 
		-- name: Invigorating Earthsiege Health Regen 
		-- type: gem 
	},
}

function ProculasGem:OnInitialize()
	Proculas:addProcList('Gems',PROCS)
end
