--
-- Proculas: Hunter Procs
-- Created by Clorell/Keruni of Argent Dawn [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasHunter = Proculas:NewModule("HunterProcs")

local PROCS = {
	[6150] = {
		name = "Quick Shots",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 143 
		-- name: Quick Shots 
		-- type: HUNTER 
	},
	[53257] = {
		name = "Cobra Strikes",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 144 
		-- name: Cobra Strikes 
		-- type: HUNTER 
	},
	[56453] = {
		name = "Lock and Load",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 208 
		-- name: Lock and Load 
		-- type: HUNTER 
	},
	[53220] = {
		name = "Improved Steady Shot",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 209 
		-- name: Improved Steady Shot 
		-- type: HUNTER 
	},
}

function ProculasHunter:OnInitialize()
	Proculas:addProcList('HUNTER',PROCS)
end
