--
-- Proculas: Hunter Procs
-- Created by Clorell of Hellscream [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

if select(2, UnitClass("player")) ~= "HUNTER" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasHunter = Proculas:NewModule("HunterProcs")

local PROCS = {
	[6150] = {
		name = "Quick Shots",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 143 
		-- name: Quick Shots 
		-- type: HUNTER 
	},
	[53257] = {
		name = "Cobra Strikes",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 144 
		-- name: Cobra Strikes 
		-- type: HUNTER 
	},
	[56453] = {
		name = "Lock and Load",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 208 
		-- name: Lock and Load 
		-- type: HUNTER 
	},
	[53220] = {
		name = "Improved Steady Shot",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 209 
		-- name: Improved Steady Shot 
		-- type: HUNTER 
	},
	[57669] = {
		name = "Hunting Party",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 1,
		-- Proc Info
		-- ID: 268 
		-- name: Hunting Party 
		-- type: HUNTER 
	},
	[34501] = {
		name = "Expose Weakness",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 270 
		-- name: Expose Weakness 
		-- type: HUNTER 
	},
	[34833] = {
		name = "Master Tactician",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 271 
		-- name: Master Tactician 
		-- type: HUNTER 
	},
	[34834] = {
		name = "Master Tactician",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 271 
		-- name: Master Tactician 
		-- type: HUNTER 
	},
	[34835] = {
		name = "Master Tactician",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 271 
		-- name: Master Tactician 
		-- type: HUNTER 
	},
	[34836] = {
		name = "Master Tactician",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 271 
		-- name: Master Tactician 
		-- type: HUNTER 
	},
	[34837] = {
		name = "Master Tactician",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 271 
		-- name: Master Tactician 
		-- type: HUNTER 
	},
	[64861] = {
		name = "Precision Shots",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 283 
		-- name: Precision Shots 
		-- type: HUNTER 
	},
	[53254] = {
		name = "Wild Quiver Auto Shot",
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 284 
		-- name: Wild Quiver Auto Shot 
		-- type: HUNTER 
	},
	[64861] = {
		name = "",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 299 
		-- name:  
		-- type: HUNTER 
	},
}

function ProculasHunter:OnInitialize()
	Proculas:addProcList('HUNTER',PROCS)
end
