--
-- Proculas: Paladin Procs
-- Created by Clorell of US Hellscream
--
-- Generated by ProcDB 2.0
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local PaladinProcs = Proculas:NewModule("PaladinProcs")

if not Proculas.enabled then
	return nil
end

local PROCS = {
	[53489] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=0}, -- Proc #1: The Art of War
	[59578] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=0}, -- Proc #1: The Art of War
	[54203] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=0}, -- Proc #2: Sheath of Light
	[20050] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=0}, -- Proc #3: Vengeance
	[20052] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=0}, -- Proc #3: Vengeance
	[20053] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=0}, -- Proc #3: Vengeance
	[61840] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=0}, -- Proc #4: Righteous Vengeance
}

function PaladinProcs:OnInitialize()
	Proculas:addProcList('PALADIN',PROCS)
end