--
-- Proculas: Priest Procs
-- Created by Clorell/Keruni of Argent Dawn [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

if select(2, UnitClass("player")) ~= "PRIEST" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasPriest = Proculas:NewModule("PriestProcs")

local PROCS = {
	[33151] = {
		name = "Surge of Light",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 129 
		-- name: Surge of Light 
		-- type: PRIEST 
	},
	[34754] = {
		name = "Clearcasting",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 130 
		-- name: Clearcasting 
		-- type: PRIEST 
	},
	[14893] = {
		name = "Inspiration",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 211 
		-- name: Inspiration 
		-- type: PRIEST 
	},
	[15357] = {
		name = "Inspiration",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 212 
		-- name: Inspiration 
		-- type: PRIEST 
	},
	[15359] = {
		name = "Inspiration",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 213 
		-- name: Inspiration 
		-- type: PRIEST 
	},
	[15269] = {
		name = "Blackout",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 265 
		-- name: Blackout 
		-- type: PRIEST 
	},
}

function ProculasPriest:OnInitialize()
	Proculas:addProcList('PRIEST',PROCS)
end
