--
-- Proculas: Relic Procs
-- Created by Clorell of Hellscream [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasRelic = Proculas:NewModule("RelicProcs")

if not Proculas.enabled then
	return nil
end

local PROCS = {
	[40706] = {
		spellID = 60819,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 45 
		-- name: Libram of Reciprocation 
		-- type: libram 
	},
	[33503] = {
		spellID = 43747,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 46 
		-- name: Libram of Divine Judgement 
		-- type: libram 
	},
	[33510] = {
		spellID = 43740,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 43 
		-- name: Idol of the Unseen Moon 
		-- type: idol 
	},
	[38295] = {
		spellID = 52021,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 44 
		-- name: Idol of the Wastes 
		-- type: idol 
	},
	[33509] = {
		spellID = 43738,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 216 
		-- name: Idol of Terror 
		-- type: idol 
	},
	[47671] = {
		spellID = 67358,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 343 
		-- name: Idol of Flaring Growth 
		-- type: idol 
	},
	[40715] = {
		spellID = 60828,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 50 
		-- name: Sigil of Haunted Dreams 
		-- type: sigil 
	},
	[47673] = {
		spellID = 67383,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 320 
		-- name: Sigil of Virulence 
		-- type: sigil 
	},
	[45144] = {
		spellID = 64963,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 358 
		-- name: Sigil of Deflection 
		-- type: sigil 
	},
	[47672] = {
		spellID = 67380,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 359 
		-- name: Sigil of Insolence 
		-- type: sigil 
	},
	[33506] = {
		spellID = 43751,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 47 
		-- name: Skycall Totem 
		-- type: totem 
	},
	[33507] = {
		spellID = 43749,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 48 
		-- name: Stonebreaker's Totem 
		-- type: totem 
	},
	[37575] = {
		spellID = 48838,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 49 
		-- name: Totem of the Tundra 
		-- type: totem 
	},
	[47667] = {
		spellID = 67391,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 330 
		-- name: Totem of Quaking Earth 
		-- type: totem 
	},
	[47666] = {
		spellID = 67385,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 333 
		-- name: Totem of Electrifying Wind 
		-- type: totem 
	},
}

function ProculasRelic:OnInitialize()
	Proculas:addProcList('Items',PROCS)
end
