--
-- Proculas: Ring Procs
-- Created by Clorell of Hellscream [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasRing = Proculas:NewModule("RingProcs")

if not Proculas.enabled then
	return nil
end

local PROCS = {
	[44308] = {
		spellID = 60318,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 41 
		-- name: Signet of Edward the Odd 
		-- type: ring 
	},
	[50399] = {
		spellID = 72418,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 344 
		-- name: Ashen Band of Unmatched Wisdom 
		-- type: ring 
	},
	[50397] = {
		spellID = 72416,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 351 
		-- name: Ashen Band of Unmatched Destruction 
		-- type: ring 
	},
	[50401] = {
		spellID = 72412,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 352 
		-- name: Ashen Band of Unmatched Vengeance 
		-- type: ring 
	},
	[50403] = {
		spellID = 72414,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 353 
		-- name: Ashen Band of Unmatched Courage 
		-- type: ring 
	},
	[50400] = {
		spellID = 72418,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 360 
		-- name: Ashen Band of Endless Wisdom 
		-- type: ring 
	},
}

function ProculasRing:OnInitialize()
	Proculas:addProcList('Items',PROCS)
end
