--
-- Proculas: Rogue Procs
-- Created by Clorell of Hellscream [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasRogue = Proculas:NewModule("RogueProcs")

if not Proculas.enabled then
	return nil
end

local PROCS = {
	[35548] = {
		name = "Combat Potency",
		types = {"SPELL_ENERGIZE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 325 
		-- name: Combat Potency 
		-- type: ROGUE 
	},
	[14181] = {
		name = "Relentless Strikes",
		types = {"SPELL_ENERGIZE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 326 
		-- name: Relentless Strikes 
		-- type: ROGUE 
	},
	[51585] = {
		name = "Blade Twisting",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 327 
		-- name: Blade Twisting 
		-- type: ROGUE 
	},
}

function ProculasRogue:OnInitialize()
	Proculas:addProcList('ROGUE',PROCS)
end
