--
-- Proculas: Shaman Procs
-- Created by Clorell of Hellscream [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

if select(2, UnitClass("player")) ~= "SHAMAN" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasShaman = Proculas:NewModule("ShamanProcs")

if not Proculas.enabled then
	return nil
end

local PROCS = {
	[16246] = {
		name = "Clearcasting",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 136 
		-- name: Clearcasting 
		-- type: SHAMAN 
	},
	[16257] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 137 
		-- name: Flurry 
		-- type: SHAMAN 
	},
	[16277] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 138 
		-- name: Flurry 
		-- type: SHAMAN 
	},
	[16278] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 139 
		-- name: Flurry 
		-- type: SHAMAN 
	},
	[16279] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 140 
		-- name: Flurry 
		-- type: SHAMAN 
	},
	[16280] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 141 
		-- name: Flurry 
		-- type: SHAMAN 
	},
	[25504] = {
		name = "Windfury",
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 142 
		-- name: Windfury 
		-- type: SHAMAN 
	},
	[53819] = {
		name = "Maelstrom Weapon",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 289 
		-- name: Maelstrom Weapon 
		-- type: SHAMAN 
	},
	[53818] = {
		name = "Maelstrom Weapon",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 290 
		-- name: Maelstrom Weapon 
		-- type: SHAMAN 
	},
	[53816] = {
		name = "Maelstrom Weapon",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 291 
		-- name: Maelstrom Weapon 
		-- type: SHAMAN 
	},
	[53817] = {
		name = "Maelstrom Weapon",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 292 
		-- name: Maelstrom Weapon 
		-- type: SHAMAN 
	},
	[53814] = {
		name = "Maelstrom Weapon",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 293 
		-- name: Maelstrom Weapon 
		-- type: SHAMAN 
	},
	[39805] = {
		name = "Lightning Overload",
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 304 
		-- name: Lightning Overload 
		-- type: SHAMAN 
	},
}

function ProculasShaman:OnInitialize()
	Proculas:addProcList('SHAMAN',PROCS)
end
