--
-- Proculas: Shaman Procs
-- Created by Clorell/Keruni of Argent Dawn [US]
--
-- Generated by Proculas ProcDB Manager 1.2
-- Date Generated: 6th January 2009 at 3:59am Australia/Melbourne EST 
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasShaman = Proculas:NewModule("ShamanProcs")

local PROCS = {
	[16246] = {
		name = "Clearcasting",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 136 
		-- name: Clearcasting 
		-- type: SHAMAN 
	},
	[16257] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 137 
		-- name: Flurry 
		-- type: SHAMAN 
	},
	[16277] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 138 
		-- name: Flurry 
		-- type: SHAMAN 
	},
	[16278] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 139 
		-- name: Flurry 
		-- type: SHAMAN 
	},
	[16279] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 140 
		-- name: Flurry 
		-- type: SHAMAN 
	},
	[16280] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 141 
		-- name: Flurry 
		-- type: SHAMAN 
	},
	[25504] = {
		name = "Windfury",
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 142 
		-- name: Windfury 
		-- type: SHAMAN 
	},
}

function ProculasShaman:OnInitialize()
	Proculas:addProcList('SHAMAN',PROCS)
	Proculas:Print("Shaman Procs Loaded")
end
