--
-- Proculas: Special Procs
-- Created by Clorell/Keruni of Argent Dawn [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasSpecial = Proculas:NewModule("SpecialProcs")

local PROCS = {
	[60234] = {
		name = "Greatness",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 302 
		-- name: Greatness 
		-- type: special 
	},
	[60235] = {
		name = "Greatness",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 302 
		-- name: Greatness 
		-- type: special 
	},
	[60229] = {
		name = "Greatness",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 302 
		-- name: Greatness 
		-- type: special 
	},
	[60233] = {
		name = "Greatness",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 302 
		-- name: Greatness 
		-- type: special 
	},
}

function ProculasSpecial:OnInitialize()
	Proculas:addProcList('Special',PROCS)
end
