--
-- Proculas: Warlock Procs
-- Created by Clorell/Keruni of Argent Dawn [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

if select(2, UnitClass("player")) ~= "WARLOCK" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasWarlock = Proculas:NewModule("WarlockProcs")

local PROCS = {
	[17941] = {
		name = "Nightfall",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 108 
		-- name: Nightfall 
		-- type: WARLOCK 
	},
	[54274] = {
		name = "Backdraft",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 109 
		-- name: Backdraft 
		-- type: WARLOCK 
	},
	[54276] = {
		name = "Backdraft",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 110 
		-- name: Backdraft 
		-- type: WARLOCK 
	},
	[54277] = {
		name = "Backdraft",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 111 
		-- name: Backdraft 
		-- type: WARLOCK 
	},
	[61595] = {
		name = "Demonic Soul",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 264 
		-- name: Demonic Soul 
		-- type: WARLOCK 
	},
	[47383] = {
		name = "Molten Core",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 266 
		-- name: Molten Core 
		-- type: WARLOCK 
	},
}

function ProculasWarlock:OnInitialize()
	Proculas:addProcList('WARLOCK',PROCS)
end
