--
-- Proculas: Warlock Procs
-- Created by Clorell of US Hellscream
--
-- Generated by ProcDB 2.0
--

if select(2, UnitClass("player")) ~= "WARLOCK" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local WarlockProcs = Proculas:NewModule("WarlockProcs")

if not Proculas.enabled then
	return nil
end

local PROCS = {
	[47383] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=1}, -- Proc #10: Molten Core
	[71165] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=1}, -- Proc #10: Molten Core
	[71162] = {types={"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},onSelfOnly=1}, -- Proc #10: Molten Core
}

function WarlockProcs:OnInitialize()
	Proculas:addProcList('WARLOCK',PROCS)
end