--
-- Proculas: Warrior Procs
-- Created by Clorell/Keruni of Argent Dawn [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

if select(2, UnitClass("player")) ~= "WARRIOR" then return end

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasWarrior = Proculas:NewModule("WarriorProcs")

local PROCS = {
	[12966] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 118 
		-- name: Flurry 
		-- type: WARRIOR 
	},
	[12967] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 119 
		-- name: Flurry 
		-- type: WARRIOR 
	},
	[12968] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 120 
		-- name: Flurry 
		-- type: WARRIOR 
	},
	[12969] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 121 
		-- name: Flurry 
		-- type: WARRIOR 
	},
	[12970] = {
		name = "Flurry",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 122 
		-- name: Flurry 
		-- type: WARRIOR 
	},
	[12880] = {
		name = "Enrage",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 123 
		-- name: Enrage 
		-- type: WARRIOR 
	},
	[14201] = {
		name = "Enrage",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 124 
		-- name: Enrage 
		-- type: WARRIOR 
	},
	[14202] = {
		name = "Enrage",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 125 
		-- name: Enrage 
		-- type: WARRIOR 
	},
	[14203] = {
		name = "Enrage",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 126 
		-- name: Enrage 
		-- type: WARRIOR 
	},
	[14204] = {
		name = "Enrage",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 127 
		-- name: Enrage 
		-- type: WARRIOR 
	},
	[46916] = {
		name = "Bloodsurge",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 128 
		-- name: Bloodsurge 
		-- type: WARRIOR 
	},
	[50227] = {
		name = "Sword and Board",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 190 
		-- name: Sword and Board 
		-- type: WARRIOR 
	},
	[30029] = {
		name = "Rampage",
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 1,
		-- Proc Info
		-- ID: 191 
		-- name: Rampage 
		-- type: WARRIOR 
	},
}

function ProculasWarrior:OnInitialize()
	Proculas:addProcList('WARRIOR',PROCS)
end
