--
-- Proculas: Weapon Procs
-- Created by Clorell/Keruni of Argent Dawn [US]
--
-- Generated by Proculas ProcDB Manager 1.3
--

local Proculas = LibStub("AceAddon-3.0"):GetAddon("Proculas")
local ProculasWeapon = Proculas:NewModule("WeaponProcs")

local PROCS = {
	[9453] = {
		spellID = 11790,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 58 
		-- name: Toxic Revenger 
		-- type: dagger 
	},
	[9467] = {
		spellID = 3742,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 59 
		-- name: Gahz'rilla Fang 
		-- type: dagger 
	},
	[10625] = {
		spellID = 12685,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 60 
		-- name: Stealthblade 
		-- type: dagger 
	},
	[6660] = {
		spellID = 8348,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 61 
		-- name: Julie's Dagger 
		-- type: dagger 
	},
	[12590] = {
		spellID = 16551,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 62 
		-- name: Felstriker 
		-- type: dagger 
	},
	[31331] = {
		spellID = 38307,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 63 
		-- name: The Night Blade 
		-- type: dagger 
	},
	[43613] = {
		spellID = 59043,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 64 
		-- name: The Dusk Blade 
		-- type: dagger 
	},
	[30312] = {
		spellID = 36478,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 65 
		-- name: Infinity Blade 
		-- type: dagger 
	},
	[29182] = {
		spellID = 35353,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 66 
		-- name: Riftmaker 
		-- type: dagger 
	},
	[13218] = {
		spellID = 17331,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 67 
		-- name: Fang of the Crystal Spider 
		-- type: dagger 
	},
	[14024] = {
		spellID = 19755,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 68 
		-- name: Frightalon 
		-- type: dagger 
	},
	[12582] = {
		spellID = 16528,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 69 
		-- name: Keris of Zul'Serak 
		-- type: dagger 
	},
	[11635] = {
		spellID = 13526,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 70 
		-- name: Hookfang Shanker 
		-- type: dagger 
	},
	[6909] = {
		spellID = 13526,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 71 
		-- name: Strike of the Hydra 
		-- type: dagger 
	},
	[18816] = {
		spellID = 23267,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 90 
		-- name: Perdition's Blade 
		-- type: dagger 
	},
	[20578] = {
		spellID = 24993,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 91 
		-- name: Emerald Dragonfang 
		-- type: dagger 
	},
	[17071] = {
		spellID = 21151,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 92 
		-- name: Gutgore Ripper 
		-- type: dagger 
	},
	[19324] = {
		spellID = 24388,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 93 
		-- name: The Lobotomizer 
		-- type: dagger 
	},
	[19100] = {
		spellID = 23592,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 94 
		-- name: Electrified Dagger 
		-- type: dagger 
	},
	[14555] = {
		spellID = 18833,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 95 
		-- name: Alcor's Sunrazor 
		-- type: dagger 
	},
	[17780] = {
		spellID = 21978,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 96 
		-- name: Blade of Eternal Darkness 
		-- type: dagger 
	},
	[12531] = {
		spellID = 16454,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 97 
		-- name: Searing Needle 
		-- type: dagger 
	},
	[2164] = {
		spellID = 18107,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 98 
		-- name: Gut Ripper 
		-- type: dagger 
	},
	[32471] = {
		spellID = 40393,
		types = {"SPELL_SUMMON"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 104 
		-- name: Shard of Azzinoth 
		-- type: dagger 
	},
	[5616] = {
		spellID = 16406,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 168 
		-- name: Gutwrencher 
		-- type: dagger 
	},
	[28774] = {
		spellID = 34696,
		types = {"SPELL_LEECH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 194 
		-- name: Glaive of the Pit 
		-- type: polearm 
	},
	[17074] = {
		spellID = 21170,
		types = {"SPELL_LEECH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 195 
		-- name: Shadowstrike 
		-- type: polearm 
	},
	[17223] = {
		spellID = 21179,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 196 
		-- name: Thunderstrike 
		-- type: polearm 
	},
	[12583] = {
		spellID = 16549,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 197 
		-- name: Blackhand Doomsaw 
		-- type: polearm 
	},
	[13148] = {
		spellID = 19260,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 198 
		-- name: Chillpike 
		-- type: polearm 
	},
	[12802] = {
		spellID = 16939,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 199 
		-- name: Darkspear 
		-- type: polearm 
	},
	[13060] = {
		spellID = 16405,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 200 
		-- name: The Needler 
		-- type: polearm 
	},
	[11809] = {
		spellID = 16560,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 201 
		-- name: Flame Wrath 
		-- type: polearm 
	},
	[12243] = {
		spellID = 15662,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 202 
		-- name: Smoldering Claw 
		-- type: polearm 
	},
	[7959] = {
		spellID = 9796,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 203 
		-- name: Blight 
		-- type: polearm 
	},
	[9475] = {
		spellID = 18206,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 204 
		-- name: Diabolic Skiver 
		-- type: polearm 
	},
	[13054] = {
		spellID = 14126,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 205 
		-- name: Grim Reaper 
		-- type: polearm 
	},
	[1726] = {
		spellID = 16401,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 206 
		-- name: Poison-tipped Bone Spear 
		-- type: polearm 
	},
	[13057] = {
		spellID = 18202,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 207 
		-- name: Bloodpike 
		-- type: polearm 
	},
	[12798] = {
		spellID = 16928,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 73 
		-- name: Annihilator 
		-- type: 1haxe 
	},
	[12621] = {
		spellID = 16603,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 74 
		-- name: Demonfork 
		-- type: 1haxe 
	},
	[13408] = {
		spellID = 17506,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 75 
		-- name: Soul Breaker 
		-- type: 1haxe 
	},
	[811] = {
		spellID = 18104,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 99 
		-- name: Axe of the Deep Woods 
		-- type: 1haxe 
	},
	[19908] = {
		spellID = 24254,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 100 
		-- name: Sceptre of Smiting 
		-- type: 1haxe 
	},
	[12792] = {
		spellID = 18082,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 101 
		-- name: Volcanic Hammer 
		-- type: 1haxe 
	},
	[9419] = {
		spellID = 18083,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 102 
		-- name: Galgann's Firehammer 
		-- type: 1haxe 
	},
	[11920] = {
		spellID = 16414,
		types = {"SPELL_LEECH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 105 
		-- name: Wraith Scythe 
		-- type: 1haxe 
	},
	[32262] = {
		spellID = 40293,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 76 
		-- name: Syphon of the Nathrezim 
		-- type: 1hmace 
	},
	[30317] = {
		spellID = 36483,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 77 
		-- name: Cosmic Infuser 
		-- type: 1hmace 
	},
	[32500] = {
		spellID = 40972,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 78 
		-- name: Crystal Spire of Karabor 
		-- type: 1hmace 
	},
	[27901] = {
		spellID = 33489,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 79 
		-- name: Blackout Truncheon 
		-- type: 1hmace 
	},
	[2243] = {
		spellID = 18803,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 80 
		-- name: Hand of Edward the Odd 
		-- type: 1hmace 
	},
	[11684] = {
		spellID = 15494,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 81 
		-- name: Ironfoe 
		-- type: 1hmace 
	},
	[13183] = {
		spellID = 18203,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 82 
		-- name: Venomspitter 
		-- type: 1hmace 
	},
	[7954] = {
		spellID = 13534,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 83 
		-- name: The Shatterer 
		-- type: 1hmace 
	},
	[4090] = {
		spellID = 13496,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 84 
		-- name: Mug O' Hurt 
		-- type: 1hmace 
	},
	[17943] = {
		spellID = 21951,
		types = {"SPELL_ENERGIZE"},
		selfOnly = 1,
		-- Proc Info
		-- ID: 88 
		-- name: Fist of Stone 
		-- type: 1hmace 
	},
	[17733] = {
		spellID = 21951,
		types = {"SPELL_ENERGIZE"},
		selfOnly = 1,
		-- Proc Info
		-- ID: 89 
		-- name: Fist of Stone 
		-- type: 1hmace 
	},
	[10804] = {
		spellID = 18084,
		types = {"SPELL_LEECH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 106 
		-- name: Fist of the Damned 
		-- type: 1hmace 
	},
	[12781] = {
		spellID = 16908,
		types = {"SPELL_DISPEL"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 107 
		-- name: Serenity 
		-- type: 1hmace 
	},
	[46017] = {
		spellID = 64411,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 303 
		-- name: Val'anyr, Hammer of Ancient Kings 
		-- type: 1hmace 
	},
	[30311] = {
		spellID = 36479,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 157 
		-- name: Warp Slicer 
		-- type: 1hsword 
	},
	[28311] = {
		spellID = 34107,
		types = {"SPELL_LEECH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 158 
		-- name: Revenger 
		-- type: 1hsword 
	},
	[31332] = {
		spellID = 38308,
		types = {"SWING_EXTRA_ATTACKS"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 159 
		-- name: Blinkstrike 
		-- type: 1hsword 
	},
	[19019] = {
		spellID = 27648,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 160 
		-- name: Thunderfury, Blessed Blade of the Windseeker 
		-- type: 1hsword 
	},
	[18348] = {
		spellID = 22850,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 161 
		-- name: Quel'Serrar 
		-- type: 1hsword 
	},
	[12797] = {
		spellID = 16927,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 162 
		-- name: Frostguard 
		-- type: 1hsword 
	},
	[13361] = {
		spellID = 17484,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 163 
		-- name: Skullforge Reaver 
		-- type: 1hsword 
	},
	[6622] = {
		spellID = 8191,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 164 
		-- name: Sword of Zeal 
		-- type: 1hsword 
	},
	[13246] = {
		spellID = 17352,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 165 
		-- name: Argent Avenger 
		-- type: 1hsword 
	},
	[13953] = {
		spellID = 18278,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 166 
		-- name: Silent Fang 
		-- type: 1hsword 
	},
	[15814] = {
		spellID = 16406,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 167 
		-- name: Hameya's Slayer 
		-- type: 1hsword 
	},
	[14576] = {
		spellID = 18656,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 169 
		-- name: Ebon Hilt of Marduk 
		-- type: 1hsword 
	},
	[10847] = {
		spellID = 13049,
		types = {"SPELL_SUMMON"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 170 
		-- name: Dragon's Call 
		-- type: 1hsword 
	},
	[12777] = {
		spellID = 16898,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 171 
		-- name: Blazing Rapier 
		-- type: 1hsword 
	},
	[11817] = {
		spellID = 15602,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 172 
		-- name: Lord General's Sword 
		-- type: 1hsword 
	},
	[10803] = {
		spellID = 18088,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 173 
		-- name: Blade of the Wretched 
		-- type: 1hsword 
	},
	[10797] = {
		spellID = 16413,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 174 
		-- name: Firebreather 
		-- type: 1hsword 
	},
	[17705] = {
		spellID = 21919,
		types = {"SWING_EXTRA_ATTACKS"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 175 
		-- name: Thrash Blade 
		-- type: 1hsword 
	},
	[809] = {
		spellID = 17504,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 176 
		-- name: Bloodrazor 
		-- type: 1hsword 
	},
	[11086] = {
		spellID = 11657,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 177 
		-- name: Jang'thraze the Protector 
		-- type: 1hsword 
	},
	[7961] = {
		spellID = 9806,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 178 
		-- name: Phantom Blade 
		-- type: 1hsword 
	},
	[13035] = {
		spellID = 17511,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 179 
		-- name: Serpent Slicer 
		-- type: 1hsword 
	},
	[869] = {
		spellID = 13752,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 180 
		-- name: Dazzling Longsword 
		-- type: 1hsword 
	},
	[1265] = {
		spellID = 18208,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 181 
		-- name: Scorpion Sting 
		-- type: 1hsword 
	},
	[8223] = {
		spellID = 10351,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 182 
		-- name: Blade of the Basilisk 
		-- type: 1hsword 
	},
	[8225] = {
		spellID = 13530,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 183 
		-- name: Tainted Pierce 
		-- type: 1hsword 
	},
	[8224] = {
		spellID = 16403,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 184 
		-- name: Silithid Ripper 
		-- type: 1hsword 
	},
	[1727] = {
		spellID = 13528,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 185 
		-- name: Sword of Decay 
		-- type: 1hsword 
	},
	[13032] = {
		spellID = 17510,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 186 
		-- name: Sword of Corruption 
		-- type: 1hsword 
	},
	[14145] = {
		spellID = 18381,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 187 
		-- name: Cursed Felblade 
		-- type: 1hsword 
	},
	[44096] = {
		spellID = 59830,
		types = {"SWING_EXTRA_ATTACKS"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 188 
		-- name: Battleworn Thrash Blade 
		-- type: 1hsword 
	},
	[7717] = {
		spellID = 9632,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 85 
		-- name: Ravager 
		-- type: 2haxe 
	},
	[30316] = {
		spellID = 36479,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 234 
		-- name: Devastation 
		-- type: 2haxe 
	},
	[31318] = {
		spellID = 38282,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 235 
		-- name: Singing Crystal Axe 
		-- type: 2haxe 
	},
	[21134] = {
		spellID = 26108,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 236 
		-- name: Dark Edge of Insanity 
		-- type: 2haxe 
	},
	[19353] = {
		spellID = 21140,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 237 
		-- name: Drake Talon Cleaver 
		-- type: 2haxe 
	},
	[21856] = {
		spellID = 26693,
		types = {"SPELL_LEECH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 238 
		-- name: Neretzek, The Blood Drinker 
		-- type: 2haxe 
	},
	[13983] = {
		spellID = 18289,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 239 
		-- name: Gravestone War Axe 
		-- type: 2haxe 
	},
	[1263] = {
		spellID = 17148,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 240 
		-- name: Brain Hacker 
		-- type: 2haxe 
	},
	[13285] = {
		spellID = 17407,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 241 
		-- name: The Blackrock Slicer 
		-- type: 2haxe 
	},
	[11607] = {
		spellID = 15280,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 242 
		-- name: Dark Iron Sunderer 
		-- type: 2haxe 
	},
	[12769] = {
		spellID = 16871,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 243 
		-- name: Bleakwood Hew 
		-- type: 2haxe 
	},
	[17730] = {
		spellID = 21949,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 244 
		-- name: Gatorbite Axe 
		-- type: 2haxe 
	},
	[2291] = {
		spellID = 17153,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 245 
		-- name: Kang the Decapitator 
		-- type: 2haxe 
	},
	[9425] = {
		spellID = 10373,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 246 
		-- name: Pendulum of Doom 
		-- type: 2haxe 
	},
	[870] = {
		spellID = 18796,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 247 
		-- name: Fiery War Axe 
		-- type: 2haxe 
	},
	[12250] = {
		spellID = 13440,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 248 
		-- name: Midnight Axe 
		-- type: 2haxe 
	},
	[2299] = {
		spellID = 18199,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 249 
		-- name: Burning War Axe 
		-- type: 2haxe 
	},
	[7753] = {
		spellID = 18200,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 250 
		-- name: Bloodspiller 
		-- type: 2haxe 
	},
	[9486] = {
		spellID = 13527,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 251 
		-- name: Supercharger Battle Axe 
		-- type: 2haxe 
	},
	[13016] = {
		spellID = 13318,
		types = {"SPELL_AURA_APPLIED","SPELL_AURA_REFRESH"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 252 
		-- name: Killmaim 
		-- type: 2haxe 
	},
	[1318] = {
		spellID = 13480,
		types = {"SPELL_DAMAGE"},
		selfOnly = 0,
		-- Proc Info
		-- ID: 253 
		-- name: Night Reaver 
		-- type: 2haxe 
	},
}

function ProculasWeapon:OnInitialize()
	Proculas:addProcList('Items',PROCS)
end
